### ISSUE TITLE
[BUG] Error opening file for writing; filename='/var/log/messages', error='No such file or directory (2)'

### ISSUE THREAD

**Issue by Nikolay-Ch** [linuxserver/docker-syslog-ng#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I download container and run it. Container create folders config and log and starts/

But it cant log nothing. In main log I get this:
"Error opening file for writing; filename='/var/log/messages', error='No such file or directory (2)'"

Restarting container not helped to me.

### Steps To Reproduce

Ubuntu 20.22

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-100-generic x86_64)
- How docker service was installed: Standard docker through apt install. Docker version 26.0.0, build 2ae903e
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
   --name syslog-ng \
   --restart=unless-stopped \
   -p 514:5514/udp \
   -p 601:6601/tcp \
   -p 6514:6514/tcp \
   -e TZ=Europe/Moscow \
   -v /srv/syslog-ng/config:/config \
   -v /srv/syslog-ng/log:/var/log \
   lscr.io/linuxserver/syslog-ng
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by homerr** [comment]
Make sure you follow the documentation when creating the container, specifically making sure you set the PUID and PGID variables so that the file ownership is right.

Remove down the container and recreate following these steps;

https://github.com/linuxserver/docker-daapd/pull/75

**Comment by cypherbits** [comment]
I have this config:

```
services:
  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:latest
    container_name: syslog-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - LOG_TO_STDOUT=true
    volumes:
      - /docker/syslog-ng/config:/config
    ports:
      - 514:5514/udp
      - 601:6601/tcp
      - 6514:6514/tcp
    restart: unless-stopped
```

This error logs appears:

[2025-09-06T12:53:26.515196] Error opening file for writing; filename='/var/log/messages', error='No such file or directory (2)'
[2025-09-06T12:53:26.516750] Error opening file for writing; filename='/var/log/messages-kv.log', error='No such file or directory (2)'

Even LOG_TO_STDOUT seems to not be working for me.

@homerr
