### ISSUE TITLE
Can't reload syslog-ng

### ISSUE THREAD

**Issue by Issykul** [linuxserver/docker-syslog-ng#9]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

With `syslog-ng-ctl reload` i should be able to reload the config file.

## Current Behavior

Instead of reloading the config the container prints out this:
`Error connecting control socket, socket='/run/syslog-ng.ctl', error='No such file or directory'`

## Steps to Reproduce

1. Pull Image
2. Start Container
3. Do something or nothing to the config, doesn't matter
4. `docker exec syslog-ng syslog-ng-ctl reload` or do `docker exec -it syslog-ng bash` and run the command inside.

## Environment
**OS: Ubuntu 20.04.4 LTS**
**CPU architecture:** x86_64
**How docker service was installed: From the docker hub. Version 3.36.1**

## Command used to create docker container (run/create/compose/screenshot)

```
version: "3"
services:
  syslog-ng:
    image: linuxserver/syslog-ng:3.36.1
    container_name: syslog-ng
    environment:
      - PUID=0
      - PGID=0
      - TZ=[REDACTED]
    volumes:
      - /srv/syslog/config:/config
      - /srv/syslog/logs:/var/log
    ports:
      - 514:5514/udp
      - 601:6601/tcp
      - 6514:6514/tcp
    restart: unless-stopped
    networks:
      - syslog
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.hostname == [REDACTED]
    logging:
      driver: "json-file"
networks:
  syslog:
    external: true
```

## Docker logs

Nothing gets printed in the logs, so not relatable.
